import type { Metadata } from "next";
import "./globals.css";
import Header from "@/app/components/Header";
import {Montserrat, Rye} from "next/font/google";

const montserrat = Montserrat({ subsets:["latin"], weight:["400", "700", "900" ]});
const rye = Rye({ subsets:["latin"], weight:["400" ]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={rye.className}>
        <Header font = {montserrat}/>
        {children}
      </body>
    </html>
  );
}
